import { OrderType } from "./App";

export const urgentOrders: OrderType[] = [
    {
      id: "1",
      clientName: "Alice",
      orderNumber: 101,
      startDate: new Date("2023-01-01"),
      endDate: new Date("2023-01-10"),
      isFinished: false,
      size: 5,
    },
    {
      id: "2",
      clientName: "Bob",
      orderNumber: 102,
      startDate: new Date("2023-02-01"),
      endDate: new Date("2023-02-10"),
      isFinished: true,
      size: 3,
    },
    {
      id: "3",
      clientName: "Charlie",
      orderNumber: 103,
      startDate: new Date("2023-03-01"),
      endDate: new Date("2023-03-10"),
      isFinished: false,
      size: 4,
    },
  ];
  
  export const sampleOrders: OrderType[] = [
    {
      id: "1",
      clientName: "Alice",
      orderNumber: 101,
      startDate: new Date("2023-01-01"),
      endDate: new Date("2023-01-10"),
      isFinished: false,
      size: 5,
    },
    {
      id: "2",
      clientName: "Bob",
      orderNumber: 102,
      startDate: new Date("2023-02-01"),
      endDate: new Date("2023-02-10"),
      isFinished: true,
      size: 3,
    },
    {
      id: "3",
      clientName: "Charlie",
      orderNumber: 103,
      startDate: new Date("2023-03-01"),
      endDate: new Date("2023-03-10"),
      isFinished: false,
      size: 4,
    },
    {
      id: "4",
      clientName: "David",
      orderNumber: 104,
      startDate: new Date("2023-04-01"),
      endDate: new Date("2023-04-10"),
      isFinished: true,
      size: 2,
    },
    {
      id: "5",
      clientName: "Eva",
      orderNumber: 105,
      startDate: new Date("2023-05-01"),
      endDate: new Date("2023-05-10"),
      isFinished: false,
      size: 6,
    },
    {
      id: "6",
      clientName: "Frank",
      orderNumber: 106,
      startDate: new Date("2023-06-01"),
      endDate: new Date("2023-06-10"),
      isFinished: true,
      size: 3,
    },
    {
      id: "7",
      clientName: "Grace",
      orderNumber: 107,
      startDate: new Date("2023-07-01"),
      endDate: new Date("2023-07-10"),
      isFinished: false,
      size: 5,
    },
    {
      id: "8",
      clientName: "Henry",
      orderNumber: 108,
      startDate: new Date("2023-08-01"),
      endDate: new Date("2023-08-10"),
      isFinished: true,
      size: 4,
    },
    {
      id: "9",
      clientName: "Ivy",
      orderNumber: 109,
      startDate: new Date("2023-09-01"),
      endDate: new Date("2023-09-10"),
      isFinished: false,
      size: 7,
    },
    {
      id: "10",
      clientName: "Jack",
      orderNumber: 110,
      startDate: new Date("2023-10-01"),
      endDate: new Date("2023-10-10"),
      isFinished: true,
      size: 2,
    },
  ];
  
  export const inboxMailTitles: string[] = [
    "Welcome to Our Team!",
    "Monthly Company Performance Report",
    "Invitation: Annual General Meeting",
    "Reminder: Upcoming Team Building Event",
    "New Policy Implementation Notice",
    "Weekly Team Progress Update",
    "Staff Satisfaction Survey",
    "Urgent: IT System Maintenance Notification",
    "Quarterly Financial Summary",
    "Holiday Schedule and Office Hours",
    "Project XYZ: Milestone Achievements",
  ];